name: .NET Core
on: [push]

jobs:
  build:
    name: Build .Net Core Application    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        id: checkout_code
        uses: actions/checkout@v1
