name: .NET Core
on: [push]

jobs:
  build:
   name: Build .Net Core Application    
   runs-on: ubuntu-latest
   steps:
    - name: Checkout Code
      id: checkout_code
      uses: actions/checkout@v1
    - name: Setup .Net Core
      id: setup_net_core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
